# Generated by Django 4.2.1 on 2025-12-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(through='cursos.Inscripcion', to='cursos.estudiante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'curso'), name='unique_inscripcion'),
        ),
    ]
